### ISSUE TITLE
Wrong instruction for download - missing spaces

### ISSUE THREAD

**Issue by logictester** [ThalesGroup/application-gateway#3]
$ sudo curl -L"https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)"-o /usr/local/bin/docker-compose

Should be:

$ sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

It breaks copy/paste

**Comment by pranay-thales** [comment]
Fixed
